### ISSUE TITLE
port 3000 is a not a good default

### ISSUE THREAD

**Issue by tohagan** [ealves/protractor-recorder#29]
Since most Node projects typically use 3000 as their default port, I think it's unwise to make this the default for assisting tools like protractor-recorder since it's likely to collide with the port needed by app being tested.

**Comment by ealves** [comment]
https://github.com/ealves/protractor-recorder/commit/f66b6328c9c39986de5b40896b84965a357983ba

**Comment by tohagan** [comment]
Thanks!
