### ISSUE TITLE
Webapps with RequireJs

### ISSUE THREAD

**Issue by ealves** [ealves/protractor-recorder#3]
Problem when try to inject javascript on target page thats use require.js.

**Comment by semos** [comment]
@ealves Do you have more info on this ? 
This project looks very good and I'd be glad to help out.

I'm actually planning to use it on a browserified app so i thought this issue could be a good starting point. :)

S.

**Comment by ealves** [comment]
@semos Good to know your opinion about the project. 

Yes, the info is when you try to load socket.io after require.js, resulting to this errors:
* 'Uncaught ReferenceError: io is not defined';
* 'Uncaught Error: Mismatched anonymous define() module:...'.

This work if you add script tags to load socket.io before require.js in the target app.
So now i'm trying to load socket.io and snippet.js in iframe to avoid conflicts with AMD flows.
