### ISSUE TITLE
Any idea why this tool wont work over https?

### ISSUE THREAD

**Issue by magestican** [ealves/protractor-recorder#33]
I have been trying to get this to my testing team but I have one big issue and that is that the tool wont work for https urls, it wont record anything, an easy thing to try is https://google.com.
Any idea why or where can I make a change in the sourcecode to fix it?

**Comment by kcampion** [comment]
Same problem for me.

**Comment by assiomatica** [comment]
here is the reason:

VM512:248 Mixed Content: The page at 'https://xxxxxx.com/' was loaded over HTTPS, but requested an insecure script 'http://localhost:3000/socket.io/socket.io.js'. This request has been blocked; the content must be served over HTTPS.
I think all snippet injection have op be rewritten , probably will need a proxy or a chrome extension to inject js correctly.

**Comment by ealves** [comment]
Yes, it's the same here https://github.com/ealves/protractor-recorder/issues/1

**Comment by Iheff** [comment]
If you have the recorder app running in https, you will be able to record against https:// websites, so its not a case of 'fixing' the recorder app, more than running it differently to deal with your environment. I'm sure this could be a toggled feature in the code if you needed it.

**Comment by ealves** [comment]
Duplicate #1
