### ISSUE TITLE
It's this project alive?

### ISSUE THREAD

**Issue by assiomatica** [ealves/protractor-recorder#36]
Hi,
there are some working version around?

Thanks

**Comment by tediroca** [comment]
There have been several recent commits so I guess there is still some activity.

https://github.com/ealves/protractor-recorder/commits/master

**Comment by shanethughes** [comment]
My organization has recently picked up Protractor since we switched to Angular so I plan to commit some of my time to this project.

**Comment by shoaibuddin** [comment]
@shanethughes Not working for me. Selenium Driver keep throwing connection refuse error and Recording never start.

**Comment by phamdt** [comment]
@shoaibuddin did you ever figure out the issue?

**Comment by amorabito** [comment]
@phamdt I had to `npm install -g protractor@5.0.0` and then run `webdriver-manager update` to get the selenium drivers to work.
I run `webdriver-manager start` outside of the protractor-recorder project location so that global version is used.

**Comment by phamdt** [comment]
@ealves i think we can close this
