### ISSUE TITLE
[BUG] Recorder not starting - 404 Not Found erros

### ISSUE THREAD

**Issue by elcomerico** [ealves/protractor-recorder#38]
Hello there, 

I followed all the steps from the readme file. I get an error when I run the web driver app

http://localhost:3000/app

**Here is the console error**

`"NetworkError: 404 Not Found - http://localhost:3000/bower_components/angular-material/angular-material.css"
angular...ial.css
"NetworkError: 404 Not Found - http://localhost:3000/bower_components/angular/angular.js"
angular.js
"NetworkError: 404 Not Found - http://localhost:3000/bower_components/angular-route/angular-route.js"
angular-route.js
"NetworkError: 404 Not Found - http://localhost:3000/bower_components/angular-animate/angular-animate.js"
angular...mate.js
"NetworkError: 404 Not Found - http://localhost:3000/bower_components/angular-aria/angular-aria.js"
angular-aria.js
"NetworkError: 404 Not Found - http://localhost:3000/bower_components/angular-material/angular-material.js"
angular...rial.js
"NetworkError: 404 Not Found - http://localhost:3000/bower_components/angular-sortable-view/src/angular-sortable-view.js"
angular...view.js
"NetworkError: 404 Not Found - http://localhost:3000/bower_components/angular-route/angular-route.js"
angular-route.js
"NetworkError: 404 Not Found - http://localhost:3000/bower_components/angular-animate/angular-animate.js"
angular...mate.js
"NetworkError: 404 Not Found - http://localhost:3000/bower_components/angular-aria/angular-aria.js"
angular-aria.js
"NetworkError: 404 Not Found - http://localhost:3000/bower_components/angular-material/angular-material.js"
angular...rial.js
"NetworkError: 404 Not Found - http://localhost:3000/bower_components/angular-sortable-view/src/angular-sortable-view.js"
angular...view.js
ReferenceError: angular is not defined
app.js (line 5, col 3)
ReferenceError: angular is not defined
navbar....ller.js (line 4, col 3)
ReferenceError: angular is not defined
main.co...ller.js (line 4, col 3)
ReferenceError: angular is not defined
protrac...vice.js (line 9, col 3)
ReferenceError: angular is not defined
seleniu...vice.js (line 9, col 3)`

**Here is the screen shot**
![image](https://cloud.githubusercontent.com/assets/20914298/18099500/a1d67eb2-6e9b-11e6-8c5b-8f99a89799a2.png)

Here is what I am running
NodeJs v5.4.1
Npm 3.31.2
Bower 1.7.9
Gulp 3.9.1
Protractor 4.0.3

iMac OS X El Capitan v.10.11.2

**Comment by shanethughes** [comment]
Are you sure you ran 'npm install' before running 'bower install'?

**Comment by elcomerico** [comment]
@shanethughes So Went back and followed the steps again. Went to the root of folder of protractor-recorder. Ran npm install then, ran bower install. and It now works.!

Thank you
